services:
  - type: web
    name: mbbs-archive-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
